name          'example42/limits'
version       '0.0.2'
source        'UNKNOWN'
author        'example42'
license       'Apache License, Version 2.0'
summary       'This module installs and manages limits'
description   'UNKNOWN. Based of stdmod/puppet-skeleton-standard 0.0.2.'
project_page  'UNKNOWN'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
