name          'example42/limits'
version       '3.0.0'
source        'https://github.com/example42/puppet-limits'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module manages limits'
description   'This module manages limits. Based of stdmod/puppet-skeleton-minimal 0.0.2.'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
